### ISSUE TITLE
Great work! But I have a question, is there any way to use a character image as a condition to generate images with the same ID? 

### ISSUE THREAD

**Issue by cuijh26** [qinghew/CharacterFactory#1]

**Comment by qinghew** [comment]
This work is designed for unconditional identity-consistent generation which is different from subject-driven generation. 

If you want to use an input image as a condition, welcome to see our another work [StableIdentity](https://github.com/qinghew/StableIdentity). InstantID, PuLID and PhotoMaker are also recommended.
