### ISSUE TITLE
can i use SDv1.5，insteading of SD2.1.  And how to ?  thanks for your awesome work!

### ISSUE THREAD

**Issue by OMTHSJUHW** [qinghew/CharacterFactory#2]
can i use SDv1.5 pretrained model path,instead of **your SD-2.1 path**. because i notice in papre that this CharterFactory is plug-and-play。
--pretrained_model_name_or_path **your SD-2.1 path**

**Comment by qinghew** [comment]
The word embedding's length of SD-1.5 is 768 which is different from SD-2.1 (length: 1024). So if you want to test with SD-1.5, you should adjust many dimension settings in the codes.

**Comment by OMTHSJUHW** [comment]
got it! I will try it！ thanks for your help!

**Comment by qinghew** [comment]
^_^looking forward to see your results
