### ISSUE TITLE
生成多张图片相似问题

### ISSUE THREAD

**Issue by 1wuxinyu** [qinghew/CharacterFactory#5]
您好，基于您的代码随机生成一些人脸图片，很多五官都有点相像呢？
问题是出现在哪个地方了呢？求解
![image](https://github.com/user-attachments/assets/f32b5eda-ca59-4714-84e5-d92089f2954b)

**Comment by qinghew** [comment]
因为Stable Dffusion可用的名人名字比较少（我们只搜集到326个），先验空间比较局限，所以训练确实存在这样的问题。你可以尝试降低\lambda_2（代码里默认是8，之前试过1也可以）来提升多样性，但采样出来的id embedding的身份一致性可能会降低。
